[package]
name = "minecraft-data-rs"
version = "0.1.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
serde_json = "1.0.64"
serde_derive = "1.0.125"
serde = "1.0.125"
include_dir = "0.6.0"
