[package]
name = "minecraft-data-rs"
version = "0.2.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "A wrapper for minecraft-data"
repository = "https://github.com/Trivernis/minecraft-data-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
serde_json = "1.0.64"
serde_derive = "1.0.125"
serde = "1.0.125"
include_dir = "0.6.0"
itertools = "0.10.0"
lazy_static = "1.4.0"